Fix link to Anaconda Navigator
streamlit/docs pull request #651
Opened 2023-05-17 18:38 UTC by RadixSeven

## 📚 Context

The old link gives a 404

## 🧠 Description of Changes

* I changed the navigator link to https://docs.anaconda.com/free/navigator/

**Revised:**

Screenshots will be identical

**Current:**

Screenshots will be identical

## 💥 Impact

Size:

- [x] Small 
- [ ] Not small 

## 🌐 References

Skipping

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

2023-05-17 23:08 UTC, MathCatsAnd commented
Thanks @RadixSeven! There are two more bad links to Anaconda that I had flagged as part of a getting started update, but there shouldn't be any conflict on my end to publish this first. Feel free to get the other two links if you want. :)

https://github.com/streamlit/docs/compare/main...MathCatsAnd:streamlit-docs:getting-started-update#diff-7bfa4ef6db0176a5cb56cc78392eaf8431e49e75876a1513eafac9bff8dec06fL37

2023-05-18 09:15 UTC, snehankekre requested changes
Hi @RadixSeven,

Thank you so much for submitting a fix! 😃 As @MathCatsAnd pointed out, would you also like to fix the other two other broken links on the same page?

Replace the link below with https://docs.anaconda.com/free/anaconda/install/windows/
https://github.com/streamlit/docs/blob/985c539f605d23d1f8871d5e4cb0f988be3450ca/content/library/get-started/installation.md?plain=1#L43

Replace the link below with https://docs.anaconda.com/free/navigator/getting-started/#navigator-managing-environments
https://github.com/streamlit/docs/blob/985c539f605d23d1f8871d5e4cb0f988be3450ca/content/library/get-started/installation.md?plain=1#L49

2023-05-22 07:38 UTC, snehankekre approved these changes

2023-05-22 07:40 UTC, snehankekre commented
Fixed the remaining links on 7703145. I believe merging the correct links on the installation page outweigh waiting for the commit from OP at this time.

2023-05-22 08:07 UTC, merged